### ISSUE TITLE
ERR_CACHE_OPERATION_NOT_SUPPORTED

### ISSUE THREAD

**Issue by luojinzhang** [protomaps/protomaps.js#104]
Hi,
I got this error `ERR_CACHE_OPERATION_NOT_SUPPORTED` randomly when using protomaps.js to create a tilemap in leaflet.
The vector file is hosted in local server using express

```
const filePath = path.join(
      __dirname,
     'pmtiles'
    );

    this._app.use(serveStatic(filePath));
    this._app.listen(3000);

```

and use protomap to create a layer

```
const layer = protomaps.leafletLayer({
      url: 'http://192.168.100.222:3000/localmap.pmtiles',
    });
    layer.addTo(map);

```
![image](https://user-images.githubusercontent.com/27719764/221738176-883a4b14-8aec-41e9-a312-0a974bd58778.png)
![image](https://user-images.githubusercontent.com/27719764/221738278-02bf5239-0ec9-44b0-bdcd-15b536c236a3.png)

Does anyone know what is the problem and how to fix this error? Though I think it doesn't actually cause any visible damage.

**Comment by bdon** [comment]
Can you reproduce the problem with a server other than Express?

**Comment by luojinzhang** [comment]
I tried with http-server, it also has the same error. the Chrome version in my app is `104.0.5112.124` , `Electron: 20.3.3`, `NodeJS: 16.15.0`

**Comment by bdon** [comment]
Can you see if this issue is consistent with yours? https://github.com/webtorrent/webtorrent/issues/1193

See "Disable Cache" in Chrome DevTools makes it go away

**Comment by luojinzhang** [comment]
Oh, thanks, the error has gone after I disable cache in developer tool.

**Comment by btkfrank** [comment]
I am facing a similar issue while prototyping using pmtiles(running on node/express as well), and it failed at fetch API randomly. Is it possible to force fetch API  to no cache( via some parameter when initializing protomaps leaflet layer). As an end user, we couldn't ask user to open devtool and disable cache.

**Comment by bdon** [comment]
@btkfrank can you find a public example page where you can reproduce this consistently? is it possible it does not affect the user experience (the requests are ones being canceled) or do you see blank tiles?

**Comment by btkfrank** [comment]
> @btkfrank can you find a public example page where you can reproduce this consistently? is it possible it does not affect the user experience (the requests are ones being canceled) or do you see blank tiles?

I see blank tile like this randomly. I am using a relatively small pmtile file(maxZoom = 7) which was exported by the cli tool.
![image](https://github.com/protomaps/protomaps-leaflet/assets/5600309/2a9e18f2-a04a-415e-9028-fd9dac6269af)

**Comment by bdon** [comment]
can you reproduce this on a remotely hosted pmtiles, or just on localhost? the best would be you can upload a demo page somewhere where others can reproduce the same behavior.

**Comment by btkfrank** [comment]
> can you reproduce this on a remotely hosted pmtiles, or just on localhost? the best would be you can upload a demo page somewhere where others can reproduce the same behavior.

The original example is using the remote tile(https://data.source.coop/protomaps/openstreetmap/tiles/v3.pmtiles), which seems fine for me when running the page on localhost. I will see if I can setup a repo with my own tile.

**Comment by btkfrank** [comment]
> can you reproduce this on a remotely hosted pmtiles, or just on localhost? the best would be you can upload a demo page somewhere where others can reproduce the same behavior.
I have a small demo repo which includes one HTML file and my local tile.
https://github.com/btkfrank/protomap-leaflet

Any feedback is appreciated, thx

**Comment by btkfrank** [comment]
it seems after forcing `fetch` API uses `cache: "no-store"` solves the problem

**Comment by bdon** [comment]
I am running your example at https://github.com/btkfrank/protomap-leaflet with `npm run start` - and refreshing the page multiple times rapidly, with browser cache disabled/enabled, but haven't seen it yet:

my browser: Version 126.0.6478.127 (Official Build) (arm64)
OS: macOS 14.5

Video would also help diagnose

**Comment by btkfrank** [comment]
![grey_tile1](https://github.com/protomaps/protomaps-leaflet/assets/5600309/2c207e24-efcb-4585-87ce-dc6782292412)

**Comment by bdon** [comment]
Thanks for the video. I'm not able to reproduce it on macOS even after refreshing many times, I can try on Windows but don't have access to a Windows computer right now. Could you also see if disabling all Chrome extensions affects this? 

If anyone else encounters this on Chrome please also leave a report.

**Comment by btkfrank** [comment]
it does not seem to help after disabling all the extensions.
