### ISSUE TITLE
Documentation map error

### ISSUE THREAD

**Issue by sing78** [protomaps/protomaps.js#107]
Hi,when visiting this documentation page https://protomaps.com/docs/frontends/leaflet#vector-basemaps ,
the map of "Detroit" is not appearing (under "so you should see a map that looks like this:").

**Comment by sing78** [comment]
One question,how can I have the same colours/style of the map mentioned above?

**Comment by bdon** [comment]
Hi, it's the default when you load protomaps.js using the web API or an extract from app.protomaps.com/downloads - no custom style required.
