### ISSUE TITLE
Features disappear at zoom > 14 with Leaflet frontend

### ISSUE THREAD

**Issue by gio0v** [protomaps/protomaps.js#110]
I am still having an issue described and supposedly solved a couple of years ago: #28. My code:

```
<script src="https://unpkg.com/protomaps@latest/dist/protomaps.min.js"></script>
<script>
    const map = L.map('map')
    let paint_rules = [
              {
                dataLayer:"layername",
                symbolizer:new protomaps.LineSymbolizer({color:"red"})
              }
    ];
    var layer = protomaps.leafletLayer({url:'myfile.pmtiles', paint_rules:paint_rules, maxDataZoom:22})
    layer.addTo(map)
</script>
```

Behavior: the max zoom is locked at 14. That is, the features added via protomaps (from PMTiles) disappear at zoom levels greater than 14 regardless of me trying to set `maxZoom:22` or `maxDataZoom:22` (or whatever other value greater than 14).

**Comment by bdon** [comment]
What is the maxzoom of your myfile.pmtiles? The `maxDataZoom` should match that, which is likely <= 15, and `maxZoom` is the maximum display level, for which 22 makes sense.

**Comment by gio0v** [comment]
Ah, I see. When I set **both** `maxDataZoom=14` (which is my data zoom level) **and** `maxZoom=22`, all works as intended. Thanks a lot.

**Comment by jvgriffis** [comment]
Hey guys - in case anyone else gets here, this turns out to be pretty sneaky! 

`maxDataZoom` **MUST** equal the `maxZoom` reported in the pmtiles header. You can't just put any ol' number in there, otherwise it will just stop at 14. I spent way too many hours on that.
