### ISSUE TITLE
Zoom transitions look odd with partial opacity

### ISSUE THREAD

**Issue by gio0v** [protomaps/protomaps.js#111]
If polygons are filled with partial opacity, when zooming in our out using the Leaflet frontend there is a weird flickering artifact where polygons seem to not appear with same opacity for some milliseconds.

@bdon, I think I found a mention [of yours from a conversation a couple of years old](https://gist.github.com/makella/950a7baee78157bf1c315a7c2ea191e7
) where you seemingly have described the same issue: "it can get a little funky when zoom transitions happen with partial opacity polygons because there can be two tiles simultaneously blended and it looks darker."

Is there any known way to prevent that from happening? Although I am in deep love with your PMTiles, which I just found out about (I am surprised it didn't become standard already, given the enormous benefits it brings in terms of disk space and performance), unfortunately the opacity issue is a no-go for my work application. This makes me really sad because I don't want to ever look back to other vector tiles (and I must use Leaflet, so can't turn to MapLibre, where it would be seemingly possible to use PMTiles without the opacity issue)

**Comment by bdon** [comment]
you can try:

1. turn off `fadeAnimation` in Leaflet so it doesn't show multiple overlapping tiles. https://leafletjs.com/reference.html#map-fadeanimation, or even `zoomAnimation`

2. Set the background color of the map to a solid color at 100% alpha.

3. use a leaflet adapter around MapLibre so you can use maplibre rendering with the leaflet API.

**Comment by gio0v** [comment]
Thanks for the suggestions! My reactions:

1. what did the trick was setting `zoomAnimation` to false. That prevents the issue. Unfortunately, however, with that setting off the zooming looks very ugly - with map areas flickering until next tiles are loaded.
2. I did not understand that one. Wouldn't that simply mean giving up on the opacity? I only have one layer over OSM tiles. So, setting such layer's background to a solid color at 100% alpha defeats my purpose of having opacity, doesn't it?
3. I got very interested in that option. Do you know of any example of how to use Protomaps with such adapters? (the only adapter I know is [maplibre-gl-leaflet](https://github.com/maplibre/maplibre-gl-leaflet), but I couldn't find any examples of using PMTiles). Or, alternatively, if it is possible to load PMTiles directly with those adapters and then style the map with standard Leaflet or Maplibre APIs, that could do the trick too.

**Comment by bdon** [comment]
@gio0v regarding 2) if your data was combined with an opaque layer than yes, I don't think it would be possible. 

Did you end up getting the maplibre adapter working?
