### ISSUE TITLE
typescript errors prevent next build

### ISSUE THREAD

**Issue by tarngerine** [protomaps/protomaps.js#17]
not a blocker, i can just disable typescript on the next app (prototype so it's okay), but im guessing the error is throwing because it's a `.ts` file but it doesnt actually have types?

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1629901/121461238-132c6d00-c974-11eb-95ab-be6abb263688.png">

**Comment by bdon** [comment]
Yeah, the typescript build is broken; I'm planning to fix it after I reorganize the internal APIs to support #1, #2, #7, and #13, but this won't be for a few weeks at the earliest. Will keep this issue open to track progress.

**Comment by bdon** [comment]
type check and test suite are now part of GitHub Actions CI
