### ISSUE TITLE
make easier to start

### ISSUE THREAD

**Issue by matkoniecz** [protomaps/protomaps.js#19]
>     var layer = new protomaps.LeafletLayer({url:'FILE.pmtiles OR ENDPOINT/{z}/{x}/{y}.pbf'})

Some hint how to obtain/setup/host that part would be info. I am quite involved in OpenStreetMap and I would need to research how to setup this.

For bonus points: is it viable to generate tiny area such as https://protomaps.github.io/protomaps.js/examples/leaflet.html#16/25.0397/121.5243 demo and host it on Github Pages or other similar free static hosting?

Or is it necessary to have some full-blown server or paid hosting?

**Comment by bdon** [comment]
Yes, you can download areas of up to .5 million nodes on https://protomaps.com/bundles and host them for free on GH Pages or any static server. Will increase the .5 limit as I fix more bugs.

**Comment by bdon** [comment]
@matkoniecz if you are interested in a specific area let me know how many estimated nodes it contains: https://protomaps.com/bundles I'm considering bumping the limit soon to about 1 million - 5 million nodes but need to balance resource usage. the downloads from there will always reflect the minute-level state of OSM.
