### ISSUE TITLE
Demo is missing an OpenStreetMap attribution

### ISSUE THREAD

**Issue by matkoniecz** [protomaps/protomaps.js#20]
https://protomaps.github.io/protomaps.js/examples/leaflet.html#16/25.0397/121.5243

see https://www.openstreetmap.org/copyright

I have not checked it but based on https://protomaps.com/blog/new-way-to-make-maps/ it seems certain to be OSM data

**Comment by matkoniecz** [comment]
Note https://protomaps.com/docs/pricing-licensing/

**Comment by bdon** [comment]
Thanks, do you want to open a PR adding the attribution?

**Comment by matkoniecz** [comment]
Sadly I am unlikely to have time for debugging what needs to be changed.

**Comment by matkoniecz** [comment]
Note that attribution is not "nice to have", you cannot use OSM data if you are not attributing it (some exceptions apply but AFAIK none of them applies here).

**Comment by bdon** [comment]
The attribution exists already on https://protomaps.com/map/#12/25.0375/121.5637 but the leaflet examples were missing those, thanks.
