### ISSUE TITLE
https://protomaps.com/docs/pricing-licensing/ is not fully covering an attribution - license itself should be mentioned/linked

### ISSUE THREAD

**Issue by matkoniecz** [protomaps/protomaps.js#21]
https://protomaps.com/docs/pricing-licensing/

> © OpenStreetMap should appear in the corner of your map.

It should be "© OpenStreetMap (ODbL)" or at least link https://www.openstreetmap.org/copyright to fulfil also requirement about stating license 

> You must include a notice associated with the Produced Work reasonably calculated to make any Person that uses, views, accesses, interacts with, or is otherwise exposed to the Produced Work aware that Content was obtained from the Database, Derivative Database, or the Database as part of a Collective Database, and that it is available under this License.

note "and that it is available under this License"

**Comment by bdon** [comment]
Updated https://protomaps.com/docs/pricing-licensing/ with example HTML snippet linking to ODbL
