### ISSUE TITLE
Max Zoom is hardcoded to 14 for Leaflet

### ISSUE THREAD

**Issue by photomattmills** [protomaps/protomaps.js#28]
Just what it says on the tin. I'm using Mapbox Vector Tiles, but I noticed a lot of the buildings weren't loading; this is because Mapbox only loads big buildings at zoom level 14, and smaller ones start at 15. I opened pull #27 with a potential (small) solution, but I'm open to other ways of fixing this too. Thanks!

**Comment by gio0v** [comment]
I was about to post a new issue when I found this closed one. I am using:

```
<script src="https://unpkg.com/protomaps@latest/dist/protomaps.min.js"></script>
<script>
    const map = L.map('map')
    let paint_rules = [
              {
                dataLayer:"layername",
                symbolizer:new protomaps.LineSymbolizer({color:"red"})
              }
    ];
    var layer = protomaps.leafletLayer({url:'myfile.pmtiles', paint_rules:paint_rules, maxZoom:22})
    layer.addTo(map)
</script>
```

Weirdly, I am still having that problem of having the max zoom locked at 14. The features from protomaps disappear at zoom levels equal or greater than 15.
