### ISSUE TITLE
Crashing/deadlock in Safari 15 / WebKit (macOS, iOS)

### ISSUE THREAD

**Issue by bdon** [protomaps/protomaps.js#57]
webkit issue tracker: https://bugs.webkit.org/show_bug.cgi?id=230751

**Comment by bdon** [comment]
same bug with reproducible test case: https://bugs.webkit.org/show_bug.cgi?id=231157

**Comment by bdon** [comment]
Safari Technology Preview 137 seems to not have this problem anymore https://developer.apple.com/safari/download/ and does not crash on the test cases linked above; some other versions before also work, but I can't download old versions to determine exactly which one.

**Comment by bdon** [comment]
See comment on https://bugs.webkit.org/show_bug.cgi?id=231157#c6 for technical resolution to isolated test case. Try to reproduce in real-world maps on Safari Technology Preview 137 or 138 - from my testing M1 seems easier to reproduce than x86.

**Comment by bdon** [comment]
WebKit bug has been marked as resolved https://bugs.webkit.org/show_bug.cgi?id=231157#c6 so closing this issue for now, though there are still some Safari 15 + M1 Mac issues being reported - please open new issue if anyone can reproduce those

**Comment by thisisaaronland** [comment]
FYI, I have seen this problem resolved in Safari/WebKit instances that self-report as `Mac OS X 10_15_7` or higher which is the case in the technology preview Safari builds. So far this has not yet been resolved in iOS 15.4 betas.
