### ISSUE TITLE
Static maps

### ISSUE THREAD

**Issue by bdon** [protomaps/protomaps.js#7]
It should be easy to render a map to a canvas element without Leaflet.

Some questions:

* Should only integer zoom levels be allowed, or fractional zooms?
* The non-module, bundled library should not have a hard dependency on Leaflet
* What should be API for a static map be like? Probably something like (center_lat, center_lon, zoom_level), and then we need to re-implement leaflet-like logic to figure out how many tiles to request based on the width and height of the canvas element.

A primary use case should be integration with D3.js, where D3-controlled, SVG-rendered elements can match projections with a crisp basemap on a background canvas element.

**Comment by KristofKoch** [comment]
Hi @bdon - awesome project! In my eyes something like (lower_left_lat, lower_left_lon, upper_right_lat, upper_right_lon) might be useful too – think of a webpage with elastic design and you want to make sure your area of interest is depicted in all its canvas filling glory.

**Comment by bdon** [comment]
I agree that defining a bounding box is useful. A few points to consider:

1. One way of doing it is defining (minX, minY, maxX, maxY) and doing the equivalent of leaflet FitBounds. That means that the canvas would be rendered to contain the given bbox, likely with some padding, and rounded to the nearest integer zoom level.
 This would also correctly handle the bbox and the canvas aspect ratio not matching.
2. We need to consider the proposed use case of using canvas as a basemap background for a d3 or other visualization. In that case, it may make sense to support fractional zooms: I think it's better to think about the important visualization overlay layer as "owning" the map projection, and PM.JS static rendering should be flexible to match the projection (the way geographic coordinates are transformed into screen coordinates).
3. Supporting fractional zooms introduces some complexity that affects other parts of the rendering. The first part is that it makes labeling more complicated, because you can encounter certain label layouts that will never occur at integer zooms, making it difficult to debug.
4. If fractional zooms are supported, then zoom-dependent map stylesheets and lambdas all need to support non-integer zooms as inputs. 
5. It seems very useful to allow rotation of static maps (affine transformation of tile coordinate system + rotation of label layout). This will very likely never be supported well in Leaflet for good reasons, see https://github.com/Leaflet/Leaflet/issues/268

**Comment by bdon** [comment]
another approach: the internal API always renders at a integer zoom, but the "static" map mode can apply a fractional scaling to make the map exactly fit an arbitrary bounding box. This could get confusing if the coordinate system is thought of as "client CSS coordinates". It might be okay if the fractional scaling case is exceptional.

**Comment by bdon** [comment]
Going to punt on rotation/fractional zooms until there is a use case.
