### ISSUE TITLE
From Where I can get Example of svg as icon for point feature?.

### ISSUE THREAD

**Issue by chakravarthi-vl** [protomaps/protomaps.js#86]

**Comment by bdon** [comment]
There's no clear examples on this currently - planning on pulling in https://github.com/protomaps/protosprites into this repo - but essentially you need to render your SVGs using that library in a PointSymbolizer. Will update this issue when progress happens. Thanks!

**Comment by bdon** [comment]
Live example is here now:

https://js.protomaps.com/examples/sprites.html

https://github.com/protomaps/protomaps.js/blob/master/examples/sprites.html
