### ISSUE TITLE
"Unimplemented type: 3" error in protomaps.min.js

### ISSUE THREAD

**Issue by EricGrange** [protomaps/protomaps.js#95]
Just downloaded a small map

https://protomaps.com/downloads/small_map/a6f512ca-0157-4ca0-8229-9aecb99dc75b

and placed the files on a server, it "works", but with occasional blank tiles (that go away when scrolling or refreshing), and the console log fills up with "Unimplemented type: 3".

The bundled files refer to https://unpkg.com/protomaps@0.7.0/dist/protomaps.min.js which seems to be quite outdated judging by the versions in the  commits here.

**Comment by EricGrange** [comment]
This can be fixed by changing the js & css references to

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/protomaps@1.19.0/dist/protomaps.min.js"></script>

and the layer assignment line in the js to

    layer = protomaps.leafletLayer({attribution:'<a href="https://protomaps.com">Protomaps</a> © <a

so it appears it's just the download script on the server that is out of date

**Comment by bdon** [comment]
@EricGrange thanks, I've updated the `leaflet.html` and `gl.html` to the latest versions, `protomaps` v1.19.0 and `pmtiles` v 1.0.4. Can you give it another try to ensure it's working?

**Comment by bdon** [comment]
@EricGrange this should be fixed now as well, was missing CSRF tokens on that page.

**Comment by bdon** [comment]
The download server now doesn't include bundled code to avoid this issue; please refer to the examples in this repo which will have the latest major/minor/patch version specified.
