### ISSUE TITLE
Demo called JSON style in Readme broken

### ISSUE THREAD

**Issue by pcmill** [protomaps/protomaps.js#98]
The demo located here: https://js.protomaps.com/examples/json_style.html linked in the readme gives errors in the console like: `Error: Tile 14 13723 7013 not found in archive`. 

Seemingly only part of the map is loaded and scrolling gives more errors.

**Comment by bdon** [comment]
see https://github.com/protomaps/PMTiles/issues/35

**Comment by bdon** [comment]
I've suppressed these error messages in 1.20.2

Thanks!
